/** Generated by YAKINDU Statechart Tools code generator. */

#include "Robot_template.h"
#include "../src/sc_types.h"

/*! \file Implementation of the state machine 'robot_template'
*/

/* prototypes of all internal functions */
static void enact_main_region_OFF(Robot_template* handle);
static void enact_main_region_DRIVE_UP_HILL_r1_DRIVING(Robot_template* handle);
static void enact_main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT(Robot_template* handle);
static void enact_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF(Robot_template* handle);
static void enact_main_region_DRIVE_UP_HILL_r1_SLOW_DOWN(Robot_template* handle);
static void enact_main_region_DRIVE_UP_HILL_r1_TURN_AROUND(Robot_template* handle);
static void enseq_main_region_OFF_default(Robot_template* handle);
static void enseq_main_region_DRIVE_UP_HILL_default(Robot_template* handle);
static void enseq_main_region_DRIVE_UP_HILL_r1_DRIVING_default(Robot_template* handle);
static void enseq_main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT_default(Robot_template* handle);
static void enseq_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF_default(Robot_template* handle);
static void enseq_main_region_DRIVE_UP_HILL_r1_SLOW_DOWN_default(Robot_template* handle);
static void enseq_main_region_DRIVE_UP_HILL_r1_TURN_AROUND_default(Robot_template* handle);
static void enseq_main_region_default(Robot_template* handle);
static void enseq_main_region_DRIVE_UP_HILL_r1_default(Robot_template* handle);
static void exseq_main_region_OFF(Robot_template* handle);
static void exseq_main_region_DRIVE_UP_HILL(Robot_template* handle);
static void exseq_main_region_DRIVE_UP_HILL_r1_DRIVING(Robot_template* handle);
static void exseq_main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT(Robot_template* handle);
static void exseq_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF(Robot_template* handle);
static void exseq_main_region_DRIVE_UP_HILL_r1_SLOW_DOWN(Robot_template* handle);
static void exseq_main_region_DRIVE_UP_HILL_r1_TURN_AROUND(Robot_template* handle);
static void exseq_main_region(Robot_template* handle);
static void exseq_main_region_DRIVE_UP_HILL_r1(Robot_template* handle);
static void react_main_region__entry_Default(Robot_template* handle);
static void react_main_region_DRIVE_UP_HILL_r1__entry_Default(Robot_template* handle);
static sc_boolean react(Robot_template* handle);
static sc_boolean main_region_OFF_react(Robot_template* handle, const sc_boolean try_transition);
static sc_boolean main_region_DRIVE_UP_HILL_react(Robot_template* handle, const sc_boolean try_transition);
static sc_boolean main_region_DRIVE_UP_HILL_r1_DRIVING_react(Robot_template* handle, const sc_boolean try_transition);
static sc_boolean main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT_react(Robot_template* handle, const sc_boolean try_transition);
static sc_boolean main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF_react(Robot_template* handle, const sc_boolean try_transition);
static sc_boolean main_region_DRIVE_UP_HILL_r1_SLOW_DOWN_react(Robot_template* handle, const sc_boolean try_transition);
static sc_boolean main_region_DRIVE_UP_HILL_r1_TURN_AROUND_react(Robot_template* handle, const sc_boolean try_transition);
static void clearInEvents(Robot_template* handle);
static void clearOutEvents(Robot_template* handle);


void robot_template_init(Robot_template* handle)
{
	sc_integer i;
	
	for (i = 0; i < ROBOT_TEMPLATE_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Robot_template_last_state;
	}
	
	
	handle->stateConfVectorPosition = 0;
	
	clearInEvents(handle);
	clearOutEvents(handle);
	
	/* Default init sequence for statechart robot_template */
	handle->iface.pushed = bool_false;
	handle->iface.distance = 0.0f;
	handle->iface.angle = 0.0f;
	handle->iface.tilt = 0.0f;
	handle->iface.y_tilt = 0.0f;
	handle->iface.prev_encoder = 0;
	handle->iface.angle_threshold = -8.0f;
	handle->iface.up = bool_true;
	handle->iface.original_error = 0;
	handle->iface.error = 0;
	handle->iface.rate = 0;
	handle->iface.rate_constant = (1.0f / 2);
	handle->iface.time = 0;
	handle->iface.left = 0;
	handle->iface.right = 0;
	handle->iface.left_turn_speed = -50;
	handle->iface.right_turn_speed = 50;
	handle->iface.left_drive_speed = 200;
	handle->iface.right_drive_speed = 202;
	handle->iface.k = 100;
	handle->iface.is_clockwise = bool_true;
	handle->iface.direction_fix = get_direction_fix(handle->iface.is_clockwise);
}

void robot_template_enter(Robot_template* handle)
{
	/* Default enter sequence for statechart robot_template */
	enseq_main_region_default(handle);
}

void robot_template_runCycle(Robot_template* handle)
{
	clearOutEvents(handle);
	for (handle->stateConfVectorPosition = 0;
		handle->stateConfVectorPosition < ROBOT_TEMPLATE_MAX_ORTHOGONAL_STATES;
		handle->stateConfVectorPosition++)
		{
			
		switch (handle->stateConfVector[handle->stateConfVectorPosition])
		{
		case Robot_template_main_region_OFF:
		{
			main_region_OFF_react(handle, bool_true);
			break;
		}
		case Robot_template_main_region_DRIVE_UP_HILL_r1_DRIVING:
		{
			main_region_DRIVE_UP_HILL_r1_DRIVING_react(handle, bool_true);
			break;
		}
		case Robot_template_main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT:
		{
			main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT_react(handle, bool_true);
			break;
		}
		case Robot_template_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF:
		{
			main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF_react(handle, bool_true);
			break;
		}
		case Robot_template_main_region_DRIVE_UP_HILL_r1_SLOW_DOWN:
		{
			main_region_DRIVE_UP_HILL_r1_SLOW_DOWN_react(handle, bool_true);
			break;
		}
		case Robot_template_main_region_DRIVE_UP_HILL_r1_TURN_AROUND:
		{
			main_region_DRIVE_UP_HILL_r1_TURN_AROUND_react(handle, bool_true);
			break;
		}
		default:
			break;
		}
	}
	
	clearInEvents(handle);
}

void robot_template_exit(Robot_template* handle)
{
	/* Default exit sequence for statechart robot_template */
	exseq_main_region(handle);
}

sc_boolean robot_template_isActive(const Robot_template* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < ROBOT_TEMPLATE_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Robot_template_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean robot_template_isFinal(const Robot_template* handle)
{
(void)(handle);
return bool_false;

}

sc_boolean robot_template_isStateActive(const Robot_template* handle, Robot_templateStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Robot_template_main_region_OFF :
			result = (sc_boolean) (handle->stateConfVector[SCVI_ROBOT_TEMPLATE_MAIN_REGION_OFF] == Robot_template_main_region_OFF
			);
			break;
		case Robot_template_main_region_DRIVE_UP_HILL :
			result = (sc_boolean) (handle->stateConfVector[SCVI_ROBOT_TEMPLATE_MAIN_REGION_DRIVE_UP_HILL] >= Robot_template_main_region_DRIVE_UP_HILL
				&& handle->stateConfVector[SCVI_ROBOT_TEMPLATE_MAIN_REGION_DRIVE_UP_HILL] <= Robot_template_main_region_DRIVE_UP_HILL_r1_TURN_AROUND);
			break;
		case Robot_template_main_region_DRIVE_UP_HILL_r1_DRIVING :
			result = (sc_boolean) (handle->stateConfVector[SCVI_ROBOT_TEMPLATE_MAIN_REGION_DRIVE_UP_HILL_R1_DRIVING] == Robot_template_main_region_DRIVE_UP_HILL_r1_DRIVING
			);
			break;
		case Robot_template_main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT :
			result = (sc_boolean) (handle->stateConfVector[SCVI_ROBOT_TEMPLATE_MAIN_REGION_DRIVE_UP_HILL_R1_CALIBRATE_TILT] == Robot_template_main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT
			);
			break;
		case Robot_template_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF :
			result = (sc_boolean) (handle->stateConfVector[SCVI_ROBOT_TEMPLATE_MAIN_REGION_DRIVE_UP_HILL_R1_AVOID_CLIFF] == Robot_template_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF
			);
			break;
		case Robot_template_main_region_DRIVE_UP_HILL_r1_SLOW_DOWN :
			result = (sc_boolean) (handle->stateConfVector[SCVI_ROBOT_TEMPLATE_MAIN_REGION_DRIVE_UP_HILL_R1_SLOW_DOWN] == Robot_template_main_region_DRIVE_UP_HILL_r1_SLOW_DOWN
			);
			break;
		case Robot_template_main_region_DRIVE_UP_HILL_r1_TURN_AROUND :
			result = (sc_boolean) (handle->stateConfVector[SCVI_ROBOT_TEMPLATE_MAIN_REGION_DRIVE_UP_HILL_R1_TURN_AROUND] == Robot_template_main_region_DRIVE_UP_HILL_r1_TURN_AROUND
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clearInEvents(Robot_template* handle)
{
}

static void clearOutEvents(Robot_template* handle)
{
}



sc_boolean robot_templateIface_get_pushed(const Robot_template* handle)
{
	return handle->iface.pushed;
}
void robot_templateIface_set_pushed(Robot_template* handle, sc_boolean value)
{
	handle->iface.pushed = value;
}
float robot_templateIface_get_distance(const Robot_template* handle)
{
	return handle->iface.distance;
}
void robot_templateIface_set_distance(Robot_template* handle, float value)
{
	handle->iface.distance = value;
}
float robot_templateIface_get_angle(const Robot_template* handle)
{
	return handle->iface.angle;
}
void robot_templateIface_set_angle(Robot_template* handle, float value)
{
	handle->iface.angle = value;
}
float robot_templateIface_get_tilt(const Robot_template* handle)
{
	return handle->iface.tilt;
}
void robot_templateIface_set_tilt(Robot_template* handle, float value)
{
	handle->iface.tilt = value;
}
float robot_templateIface_get_y_tilt(const Robot_template* handle)
{
	return handle->iface.y_tilt;
}
void robot_templateIface_set_y_tilt(Robot_template* handle, float value)
{
	handle->iface.y_tilt = value;
}
uint16_t robot_templateIface_get_prev_encoder(const Robot_template* handle)
{
	return handle->iface.prev_encoder;
}
void robot_templateIface_set_prev_encoder(Robot_template* handle, uint16_t value)
{
	handle->iface.prev_encoder = value;
}
float robot_templateIface_get_angle_threshold(const Robot_template* handle)
{
	return handle->iface.angle_threshold;
}
void robot_templateIface_set_angle_threshold(Robot_template* handle, float value)
{
	handle->iface.angle_threshold = value;
}
sc_boolean robot_templateIface_get_up(const Robot_template* handle)
{
	return handle->iface.up;
}
void robot_templateIface_set_up(Robot_template* handle, sc_boolean value)
{
	handle->iface.up = value;
}
float robot_templateIface_get_original_error(const Robot_template* handle)
{
	return handle->iface.original_error;
}
void robot_templateIface_set_original_error(Robot_template* handle, float value)
{
	handle->iface.original_error = value;
}
float robot_templateIface_get_error(const Robot_template* handle)
{
	return handle->iface.error;
}
void robot_templateIface_set_error(Robot_template* handle, float value)
{
	handle->iface.error = value;
}
float robot_templateIface_get_rate(const Robot_template* handle)
{
	return handle->iface.rate;
}
void robot_templateIface_set_rate(Robot_template* handle, float value)
{
	handle->iface.rate = value;
}
float robot_templateIface_get_rate_constant(const Robot_template* handle)
{
	return handle->iface.rate_constant;
}
void robot_templateIface_set_rate_constant(Robot_template* handle, float value)
{
	handle->iface.rate_constant = value;
}
float robot_templateIface_get_time(const Robot_template* handle)
{
	return handle->iface.time;
}
void robot_templateIface_set_time(Robot_template* handle, float value)
{
	handle->iface.time = value;
}
uint16_t robot_templateIface_get_left(const Robot_template* handle)
{
	return handle->iface.left;
}
void robot_templateIface_set_left(Robot_template* handle, uint16_t value)
{
	handle->iface.left = value;
}
uint16_t robot_templateIface_get_right(const Robot_template* handle)
{
	return handle->iface.right;
}
void robot_templateIface_set_right(Robot_template* handle, uint16_t value)
{
	handle->iface.right = value;
}
float robot_templateIface_get_left_turn_speed(const Robot_template* handle)
{
	return handle->iface.left_turn_speed;
}
void robot_templateIface_set_left_turn_speed(Robot_template* handle, float value)
{
	handle->iface.left_turn_speed = value;
}
float robot_templateIface_get_right_turn_speed(const Robot_template* handle)
{
	return handle->iface.right_turn_speed;
}
void robot_templateIface_set_right_turn_speed(Robot_template* handle, float value)
{
	handle->iface.right_turn_speed = value;
}
uint16_t robot_templateIface_get_left_drive_speed(const Robot_template* handle)
{
	return handle->iface.left_drive_speed;
}
void robot_templateIface_set_left_drive_speed(Robot_template* handle, uint16_t value)
{
	handle->iface.left_drive_speed = value;
}
uint16_t robot_templateIface_get_right_drive_speed(const Robot_template* handle)
{
	return handle->iface.right_drive_speed;
}
void robot_templateIface_set_right_drive_speed(Robot_template* handle, uint16_t value)
{
	handle->iface.right_drive_speed = value;
}
float robot_templateIface_get_k(const Robot_template* handle)
{
	return handle->iface.k;
}
void robot_templateIface_set_k(Robot_template* handle, float value)
{
	handle->iface.k = value;
}
sc_boolean robot_templateIface_get_is_clockwise(const Robot_template* handle)
{
	return handle->iface.is_clockwise;
}
void robot_templateIface_set_is_clockwise(Robot_template* handle, sc_boolean value)
{
	handle->iface.is_clockwise = value;
}
int32_t robot_templateIface_get_direction_fix(const Robot_template* handle)
{
	return handle->iface.direction_fix;
}
void robot_templateIface_set_direction_fix(Robot_template* handle, int32_t value)
{
	handle->iface.direction_fix = value;
}

/* implementations of all internal functions */

/* Entry action for state 'OFF'. */
static void enact_main_region_OFF(Robot_template* handle)
{
	/* Entry action for state 'OFF'. */
	handle->iface.pushed = bool_false;
	handle->iface.distance = 0.0f;
	handle->iface.angle = 0.0f;
	clear_line(1);
	stop_kobuki();
}

/* Entry action for state 'DRIVING'. */
static void enact_main_region_DRIVE_UP_HILL_r1_DRIVING(Robot_template* handle)
{
	/* Entry action for state 'DRIVING'. */
	handle->iface.pushed = bool_false;
	handle->iface.prev_encoder = read_encoder();
	stop_kobuki();
}

/* Entry action for state 'CALIBRATE_TILT'. */
static void enact_main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT(Robot_template* handle)
{
	/* Entry action for state 'CALIBRATE_TILT'. */
	handle->iface.tilt = read_tilt_theta();
	handle->iface.y_tilt = read_tilt_psi();
	handle->iface.direction_fix = get_direction_fix(((((handle->iface.y_tilt) > (0)) == bool_true) && (handle->iface.up == bool_true)) || ((((handle->iface.y_tilt) < (0)) == bool_true) && (handle->iface.up == bool_false)));
	handle->iface.pushed = bool_false;
	handle->iface.original_error = (-13 - handle->iface.tilt);
	handle->iface.error = (-13 - handle->iface.tilt);
	handle->iface.angle = 0;
	stop_kobuki();
}

/* Entry action for state 'AVOID_CLIFF'. */
static void enact_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF(Robot_template* handle)
{
	/* Entry action for state 'AVOID_CLIFF'. */
	handle->iface.angle = 0;
	start_gyro();
	handle->iface.pushed = bool_false;
	stop_kobuki();
}

/* Entry action for state 'SLOW_DOWN'. */
static void enact_main_region_DRIVE_UP_HILL_r1_SLOW_DOWN(Robot_template* handle)
{
	/* Entry action for state 'SLOW_DOWN'. */
	handle->iface.pushed = bool_false;
	handle->iface.prev_encoder = read_encoder();
	handle->iface.distance = 0;
	handle->iface.time = handle->iface.k;
	drive_kobuki(handle->iface.left_drive_speed, handle->iface.right_drive_speed);
}

/* Entry action for state 'TURN_AROUND'. */
static void enact_main_region_DRIVE_UP_HILL_r1_TURN_AROUND(Robot_template* handle)
{
	/* Entry action for state 'TURN_AROUND'. */
	handle->iface.angle = 0;
	handle->iface.distance = 0;
	start_gyro();
	handle->iface.pushed = bool_false;
	stop_kobuki();
	handle->iface.up = bool_false;
}

/* 'default' enter sequence for state OFF */
static void enseq_main_region_OFF_default(Robot_template* handle)
{
	/* 'default' enter sequence for state OFF */
	enact_main_region_OFF(handle);
	handle->stateConfVector[0] = Robot_template_main_region_OFF;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state DRIVE_UP_HILL */
static void enseq_main_region_DRIVE_UP_HILL_default(Robot_template* handle)
{
	/* 'default' enter sequence for state DRIVE_UP_HILL */
	enseq_main_region_DRIVE_UP_HILL_r1_default(handle);
}

/* 'default' enter sequence for state DRIVING */
static void enseq_main_region_DRIVE_UP_HILL_r1_DRIVING_default(Robot_template* handle)
{
	/* 'default' enter sequence for state DRIVING */
	enact_main_region_DRIVE_UP_HILL_r1_DRIVING(handle);
	handle->stateConfVector[0] = Robot_template_main_region_DRIVE_UP_HILL_r1_DRIVING;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state CALIBRATE_TILT */
static void enseq_main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT_default(Robot_template* handle)
{
	/* 'default' enter sequence for state CALIBRATE_TILT */
	enact_main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT(handle);
	handle->stateConfVector[0] = Robot_template_main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state AVOID_CLIFF */
static void enseq_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF_default(Robot_template* handle)
{
	/* 'default' enter sequence for state AVOID_CLIFF */
	enact_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF(handle);
	handle->stateConfVector[0] = Robot_template_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state SLOW_DOWN */
static void enseq_main_region_DRIVE_UP_HILL_r1_SLOW_DOWN_default(Robot_template* handle)
{
	/* 'default' enter sequence for state SLOW_DOWN */
	enact_main_region_DRIVE_UP_HILL_r1_SLOW_DOWN(handle);
	handle->stateConfVector[0] = Robot_template_main_region_DRIVE_UP_HILL_r1_SLOW_DOWN;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state TURN_AROUND */
static void enseq_main_region_DRIVE_UP_HILL_r1_TURN_AROUND_default(Robot_template* handle)
{
	/* 'default' enter sequence for state TURN_AROUND */
	enact_main_region_DRIVE_UP_HILL_r1_TURN_AROUND(handle);
	handle->stateConfVector[0] = Robot_template_main_region_DRIVE_UP_HILL_r1_TURN_AROUND;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Robot_template* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* 'default' enter sequence for region r1 */
static void enseq_main_region_DRIVE_UP_HILL_r1_default(Robot_template* handle)
{
	/* 'default' enter sequence for region r1 */
	react_main_region_DRIVE_UP_HILL_r1__entry_Default(handle);
}

/* Default exit sequence for state OFF */
static void exseq_main_region_OFF(Robot_template* handle)
{
	/* Default exit sequence for state OFF */
	handle->stateConfVector[0] = Robot_template_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state DRIVE_UP_HILL */
static void exseq_main_region_DRIVE_UP_HILL(Robot_template* handle)
{
	/* Default exit sequence for state DRIVE_UP_HILL */
	exseq_main_region_DRIVE_UP_HILL_r1(handle);
}

/* Default exit sequence for state DRIVING */
static void exseq_main_region_DRIVE_UP_HILL_r1_DRIVING(Robot_template* handle)
{
	/* Default exit sequence for state DRIVING */
	handle->stateConfVector[0] = Robot_template_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state CALIBRATE_TILT */
static void exseq_main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT(Robot_template* handle)
{
	/* Default exit sequence for state CALIBRATE_TILT */
	handle->stateConfVector[0] = Robot_template_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state AVOID_CLIFF */
static void exseq_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF(Robot_template* handle)
{
	/* Default exit sequence for state AVOID_CLIFF */
	handle->stateConfVector[0] = Robot_template_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state SLOW_DOWN */
static void exseq_main_region_DRIVE_UP_HILL_r1_SLOW_DOWN(Robot_template* handle)
{
	/* Default exit sequence for state SLOW_DOWN */
	handle->stateConfVector[0] = Robot_template_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state TURN_AROUND */
static void exseq_main_region_DRIVE_UP_HILL_r1_TURN_AROUND(Robot_template* handle)
{
	/* Default exit sequence for state TURN_AROUND */
	handle->stateConfVector[0] = Robot_template_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for region main region */
static void exseq_main_region(Robot_template* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of robot_template.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Robot_template_main_region_OFF :
		{
			exseq_main_region_OFF(handle);
			break;
		}
		case Robot_template_main_region_DRIVE_UP_HILL_r1_DRIVING :
		{
			exseq_main_region_DRIVE_UP_HILL_r1_DRIVING(handle);
			break;
		}
		case Robot_template_main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT :
		{
			exseq_main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT(handle);
			break;
		}
		case Robot_template_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF :
		{
			exseq_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF(handle);
			break;
		}
		case Robot_template_main_region_DRIVE_UP_HILL_r1_SLOW_DOWN :
		{
			exseq_main_region_DRIVE_UP_HILL_r1_SLOW_DOWN(handle);
			break;
		}
		case Robot_template_main_region_DRIVE_UP_HILL_r1_TURN_AROUND :
		{
			exseq_main_region_DRIVE_UP_HILL_r1_TURN_AROUND(handle);
			break;
		}
		default: break;
	}
}

/* Default exit sequence for region r1 */
static void exseq_main_region_DRIVE_UP_HILL_r1(Robot_template* handle)
{
	/* Default exit sequence for region r1 */
	/* Handle exit of all possible states (of robot_template.main_region.DRIVE_UP_HILL.r1) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Robot_template_main_region_DRIVE_UP_HILL_r1_DRIVING :
		{
			exseq_main_region_DRIVE_UP_HILL_r1_DRIVING(handle);
			break;
		}
		case Robot_template_main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT :
		{
			exseq_main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT(handle);
			break;
		}
		case Robot_template_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF :
		{
			exseq_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF(handle);
			break;
		}
		case Robot_template_main_region_DRIVE_UP_HILL_r1_SLOW_DOWN :
		{
			exseq_main_region_DRIVE_UP_HILL_r1_SLOW_DOWN(handle);
			break;
		}
		case Robot_template_main_region_DRIVE_UP_HILL_r1_TURN_AROUND :
		{
			exseq_main_region_DRIVE_UP_HILL_r1_TURN_AROUND(handle);
			break;
		}
		default: break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Robot_template* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_OFF_default(handle);
}

/* Default react sequence for initial entry  */
static void react_main_region_DRIVE_UP_HILL_r1__entry_Default(Robot_template* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT_default(handle);
}

static sc_boolean react(Robot_template* handle) {
	/* State machine reactions. */
	return bool_false;
}

static sc_boolean main_region_OFF_react(Robot_template* handle, const sc_boolean try_transition) {
	/* The reactions of state OFF. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (handle->iface.pushed == bool_true)
			{ 
				exseq_main_region_OFF(handle);
				enseq_main_region_DRIVE_UP_HILL_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} 
	if ((did_transition) == (bool_false))
	{ 
		stop_kobuki();
		handle->iface.pushed = is_button_press();
		print_state(OFF);
		print_angle(read_tilt_theta());
	} 
	return did_transition;
}

static sc_boolean main_region_DRIVE_UP_HILL_react(Robot_template* handle, const sc_boolean try_transition) {
	/* The reactions of state DRIVE_UP_HILL. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			did_transition = bool_false;
		} 
	} 
	return did_transition;
}

static sc_boolean main_region_DRIVE_UP_HILL_r1_DRIVING_react(Robot_template* handle, const sc_boolean try_transition) {
	/* The reactions of state DRIVING. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((main_region_DRIVE_UP_HILL_react(handle, try_transition)) == (bool_false))
		{ 
			if (((((handle->iface.tilt) > (-2)) && ((((handle->iface.y_tilt) > (5)) || ((handle->iface.y_tilt) < (-5))) == bool_true)) && (handle->iface.up == bool_true)) || ((((handle->iface.tilt) < (2)) && ((((handle->iface.y_tilt) > (5)) || ((handle->iface.y_tilt) < (-5))) == bool_true)) && (handle->iface.up == bool_false)))
			{ 
				exseq_main_region_DRIVE_UP_HILL_r1_DRIVING(handle);
				enseq_main_region_DRIVE_UP_HILL_r1_SLOW_DOWN_default(handle);
			}  else
			{
				if (is_left_cliff() == bool_true)
				{ 
					exseq_main_region_DRIVE_UP_HILL_r1_DRIVING(handle);
					handle->iface.direction_fix = get_direction_fix(bool_true);
					enseq_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF_default(handle);
				}  else
				{
					if (is_right_cliff() == bool_true)
					{ 
						exseq_main_region_DRIVE_UP_HILL_r1_DRIVING(handle);
						handle->iface.direction_fix = get_direction_fix(bool_false);
						enseq_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF_default(handle);
					}  else
					{
						if ((((((-2) <= (handle->iface.y_tilt)) && ((handle->iface.y_tilt) < (2))) && ((-1) < (handle->iface.tilt))) && ((handle->iface.tilt) < (1))) && (handle->iface.up == bool_true))
						{ 
							exseq_main_region_DRIVE_UP_HILL_r1_DRIVING(handle);
							enseq_main_region_DRIVE_UP_HILL_r1_TURN_AROUND_default(handle);
						}  else
						{
							did_transition = bool_false;
						}
					}
				}
			}
		} 
	} 
	if ((did_transition) == (bool_false))
	{ 
		drive_kobuki(handle->iface.left_drive_speed, handle->iface.right_drive_speed);
		handle->iface.tilt = read_tilt_theta();
		handle->iface.y_tilt = read_tilt_psi();
		handle->iface.pushed = is_button_press();
		handle->iface.prev_encoder = read_encoder();
		print_state(DRIVING);
		print_angle(handle->iface.tilt);
	} 
	return did_transition;
}

static sc_boolean main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT_react(Robot_template* handle, const sc_boolean try_transition) {
	/* The reactions of state CALIBRATE_TILT. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((main_region_DRIVE_UP_HILL_react(handle, try_transition)) == (bool_false))
		{ 
			if ((((handle->iface.tilt) < (-5)) && (handle->iface.up == bool_true)) || (((handle->iface.tilt) > (5)) && (handle->iface.up == bool_false)))
			{ 
				exseq_main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT(handle);
				enseq_main_region_DRIVE_UP_HILL_r1_DRIVING_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} 
	if ((did_transition) == (bool_false))
	{ 
		handle->iface.error = (-13 - handle->iface.tilt);
		handle->iface.rate = (((handle->iface.error / handle->iface.original_error)) + handle->iface.rate_constant);
		handle->iface.left = get_speed(handle->iface.left_turn_speed, handle->iface.direction_fix, handle->iface.rate);
		handle->iface.right = get_speed(handle->iface.right_turn_speed, handle->iface.direction_fix, handle->iface.rate);
		drive_kobuki(handle->iface.left, handle->iface.right);
		handle->iface.pushed = is_button_press();
		handle->iface.tilt = read_tilt_theta();
		print_state(CALIBRATE_TILT);
		print_angle(handle->iface.tilt);
	} 
	return did_transition;
}

static sc_boolean main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF_react(Robot_template* handle, const sc_boolean try_transition) {
	/* The reactions of state AVOID_CLIFF. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((main_region_DRIVE_UP_HILL_react(handle, try_transition)) == (bool_false))
		{ 
			if ((handle->iface.angle) >= (30))
			{ 
				exseq_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF(handle);
				stop_gyro();
				enseq_main_region_DRIVE_UP_HILL_r1_DRIVING_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} 
	if ((did_transition) == (bool_false))
	{ 
		drive_kobuki((-50 * handle->iface.direction_fix), (50 * handle->iface.direction_fix));
		handle->iface.pushed = is_button_press();
		handle->iface.angle = (read_gyro() * handle->iface.direction_fix);
		print_state(AVOID_CLIFF);
		print_angle(handle->iface.angle);
	} 
	return did_transition;
}

static sc_boolean main_region_DRIVE_UP_HILL_r1_SLOW_DOWN_react(Robot_template* handle, const sc_boolean try_transition) {
	/* The reactions of state SLOW_DOWN. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((main_region_DRIVE_UP_HILL_react(handle, try_transition)) == (bool_false))
		{ 
			if ((handle->iface.time) <= (0))
			{ 
				exseq_main_region_DRIVE_UP_HILL_r1_SLOW_DOWN(handle);
				enseq_main_region_DRIVE_UP_HILL_r1_CALIBRATE_TILT_default(handle);
			}  else
			{
				if (is_left_cliff() == bool_true)
				{ 
					exseq_main_region_DRIVE_UP_HILL_r1_SLOW_DOWN(handle);
					handle->iface.direction_fix = get_direction_fix(bool_true);
					enseq_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF_default(handle);
				}  else
				{
					if (is_right_cliff() == bool_true)
					{ 
						exseq_main_region_DRIVE_UP_HILL_r1_SLOW_DOWN(handle);
						handle->iface.direction_fix = get_direction_fix(bool_false);
						enseq_main_region_DRIVE_UP_HILL_r1_AVOID_CLIFF_default(handle);
					}  else
					{
						did_transition = bool_false;
					}
				}
			}
		} 
	} 
	if ((did_transition) == (bool_false))
	{ 
		handle->iface.left = get_speed(handle->iface.left_drive_speed, 1, handle->iface.rate);
		handle->iface.right = get_speed(handle->iface.right_drive_speed, 1, handle->iface.rate);
		drive_kobuki(handle->iface.left, handle->iface.right);
		handle->iface.rate = (handle->iface.time / handle->iface.k);
		handle->iface.time = (handle->iface.time - 1);
		handle->iface.distance = update_dist(handle->iface.distance, handle->iface.prev_encoder, bool_true);
		handle->iface.tilt = read_tilt_theta();
		handle->iface.pushed = is_button_press();
		handle->iface.prev_encoder = read_encoder();
		print_state(SLOW_DOWN);
		print_dist(handle->iface.distance);
	} 
	return did_transition;
}

static sc_boolean main_region_DRIVE_UP_HILL_r1_TURN_AROUND_react(Robot_template* handle, const sc_boolean try_transition) {
	/* The reactions of state TURN_AROUND. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((main_region_DRIVE_UP_HILL_react(handle, try_transition)) == (bool_false))
		{ 
			if ((handle->iface.angle) > (180))
			{ 
				exseq_main_region_DRIVE_UP_HILL_r1_TURN_AROUND(handle);
				stop_gyro();
				enseq_main_region_DRIVE_UP_HILL_r1_DRIVING_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} 
	if ((did_transition) == (bool_false))
	{ 
		drive_kobuki((-50 * handle->iface.direction_fix), (50 * handle->iface.direction_fix));
		handle->iface.pushed = is_button_press();
		handle->iface.angle = (read_gyro() * handle->iface.direction_fix);
		print_state(TURN_AROUND);
		print_angle(handle->iface.angle);
	} 
	return did_transition;
}


